#!/usr/bin/env python3
"""
generate_content.py

Pulls data from published Google Sheets (Google Form responses + the open
mic listing) and regenerates the auto-generated Quarto content fragments
in /_generated. This is the engine behind "just approve it and the site
updates itself."

HOW THE APPROVAL WORKFLOW WORKS
--------------------------------
1. Someone fills out the "Add a Show" or "Add a Comedian" Google Form.
2. Their response lands as a new row in the linked Google Sheet.
3. Candace reviews it and types "Yes" in an "Approved" column she keeps
   on that sheet (the form doesn't create this column -- add it once by
   hand, it's just a normal spreadsheet column).
4. This script (run manually or on a schedule via GitHub Actions) pulls
   the sheet as CSV, keeps only Approved == "Yes" rows, and rewrites the
   matching file in /_generated. Quarto then renders those includes into
   shows.qmd / comedians.qmd / open-mics.qmd.
5. Nothing is ever deleted from the sheet -- rows just don't render until
   Approved is set to Yes.

SETTING THIS UP
---------------
For each Google Sheet (Shows responses, Comedians responses, Open Mic
listing), publish it to the web as CSV:
  File -> Share -> Publish to web -> select the sheet/tab -> CSV -> Publish
Paste the resulting URL into the CONFIG section below.

Each published CSV URL only exposes read-only data Google already serves
publicly once "Publish to web" is turned on -- no API key or auth needed.
"""

import csv
import io
import sys
import urllib.request
from datetime import datetime, date

# ============================== CONFIG ==============================
# Replace these with your own "Publish to web -> CSV" URLs once the forms
# and sheets exist. Leave a value as None to skip that section (it will
# be left untouched / shown as "pending" on the site).

SHOWS_CSV_URL = None        # "Add a Show" response sheet, published as CSV
COMEDIANS_CSV_URL = None    # "Add a Comedian" response sheet, published as CSV
OPENMICS_CSV_URL = None     # Open mic listing sheet, published as CSV

OUTPUT_DIR = "_generated"

# ======================================================================


def fetch_csv_rows(url: str) -> list[dict]:
    """Download a published-to-web Google Sheet CSV and return rows as dicts."""
    with urllib.request.urlopen(url, timeout=30) as response:
        raw = response.read().decode("utf-8-sig")
    reader = csv.DictReader(io.StringIO(raw))
    return [{(k or "").strip(): (v or "").strip() for k, v in row.items()} for row in reader]


def is_approved(row: dict) -> bool:
    val = (row.get("Approved") or "").strip().lower()
    return val in ("yes", "y", "true", "approved")


def is_open_mic(row: dict) -> bool:
    val = (row.get("Is this an Open Mic?") or "").strip().lower()
    return val in ("yes", "y", "true")


def escape_html(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def parse_date_safe(value: str):
    """Try a handful of common date formats; return a date object or None."""
    value = value.strip()
    for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%m/%d/%y", "%B %d, %Y", "%b %d, %Y"):
        try:
            return datetime.strptime(value, fmt).date()
        except ValueError:
            continue
    return None


# --------------------------- SHOWS ---------------------------

def build_shows_content(rows: list[dict]) -> str:
    # Rows flagged "Is this an Open Mic?" = Yes go to the Open Mics page
    # instead (see build_submitted_openmics_content below), not here.
    approved = [r for r in rows if is_approved(r) and not is_open_mic(r)]

    dated = []
    for r in approved:
        d = parse_date_safe(r.get("Date", ""))
        dated.append((d, r))
    # Undated rows sort last, but still get included
    dated.sort(key=lambda pair: (pair[0] is None, pair[0] or date.max))

    if not dated:
        return (
            "::: {.aside-note}\n"
            "No approved shows yet. Once rows are marked Approved in the "
            "sheet, they'll appear here automatically.\n"
            ":::\n"
        )

    lines = [
        "<!--",
        "AUTO-GENERATED FILE — DO NOT HAND-EDIT",
        "Regenerated by scripts/generate_content.py. Edit the source sheet",
        "and mark rows Approved instead.",
        f"Last generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "-->",
        "",
    ]

    current_month = None
    for d, r in dated:
        month_label = d.strftime("%B %Y") if d else "Date TBD"
        if month_label != current_month:
            if current_month is not None:
                lines.append("</ul>\n")
            lines.append(f"### {month_label}\n")
            lines.append('<ul class="show-list">\n')
            current_month = month_label

        name = escape_html(r.get("Show name", "Untitled Show"))
        venue = escape_html(r.get("Venue", ""))
        link = r.get("Link to where folks can buy tickets", "").strip() or "#"
        day_label = d.strftime("%a, %b %-d") if d else "TBD"
        label = f"{name} — {venue}" if venue else name

        recurring = r.get(
            "Is this a recurring show? If so, how frequently? Weekly? Monthly?", ""
        ).strip()
        recurring_tag = f" <em>({recurring})</em>" if recurring and recurring.lower() not in ("no", "n/a", "none", "") else ""

        lines.append('<li class="show-item">')
        lines.append(
            f'  <span class="show-name"><a href="{escape_html(link)}" target="_blank">{label}</a>{recurring_tag}</span>'
        )
        lines.append(f'  <span class="show-date">{day_label}</span>')
        lines.append("</li>\n")

    lines.append("</ul>")
    return "\n".join(lines)


# --------------------------- COMEDIANS ---------------------------

SOCIAL_FIELDS = [
    ("Instagram URL", "📷", "Instagram"),
    ("TikTok URL", "🎵", "TikTok"),
    ("Youtube URL", "▶️", "YouTube"),
    ("Facebook URL", "📘", "Facebook"),
    ("Website URL", "🌐", "Website"),
]


def build_comedians_content(rows: list[dict]) -> str:
    approved = [r for r in rows if is_approved(r)]

    if not approved:
        return (
            "::: {.aside-note}\n"
            "No approved comedian profiles yet. Once rows are marked "
            "Approved in the sheet, they'll appear here automatically.\n"
            ":::\n"
        )

    lines = [
        "<!--",
        "AUTO-GENERATED FILE — DO NOT HAND-EDIT",
        "Regenerated by scripts/generate_content.py. Edit the source sheet",
        "and mark rows Approved instead.",
        f"Last generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "-->",
        "",
        '<div class="comedian-grid">',
        "",
    ]

    for r in approved:
        name = escape_html(r.get("Stage Name", "").strip() or "Unnamed")
        tag = escape_html(r.get("Comedic Style (short sentence descriptor)", "").strip())
        bio = ""  # this form doesn't currently collect a separate bio field
        # Headshots submitted via Google Form file-upload land in Candace's
        # Drive, not as a public image URL, so we fall back to the
        # placeholder until a real image is manually dropped in /images
        # and its filename is used here.
        photo = r.get("Photo Filename", "").strip() or "images/placeholder-headshot.svg"

        lines.append('<div class="comedian-card">')
        lines.append(f'  <img class="comedian-photo" src="{escape_html(photo)}" alt="{name}">')
        lines.append(f'  <div class="comedian-name">{name}</div>')
        if tag:
            lines.append(f'  <div class="comedian-tag">{tag}</div>')
        if bio:
            lines.append(f'  <p class="comedian-bio">{bio}</p>')
        lines.append('  <div class="social-links">')
        for field, emoji, label in SOCIAL_FIELDS:
            url = r.get(field, "").strip()
            if url:
                lines.append(f'    <a href="{escape_html(url)}" target="_blank" title="{label}">{emoji}</a>')
        lines.append("  </div>")
        lines.append("</div>\n")

    lines.append("</div>")
    return "\n".join(lines)


# --------------------------- OPEN MICS ---------------------------

def build_submitted_openmics_content(shows_rows: list[dict]) -> str:
    """
    Rows from the SHOWS form where "Is this an Open Mic?" = Yes get their
    own small table on the Open Mics page, separate from the main
    hand-curated listing (which comes from a different source sheet).
    """
    submitted = [r for r in shows_rows if is_approved(r) and is_open_mic(r)]

    if not submitted:
        return (
            "<!-- no community-submitted open mics yet -->\n"
        )

    lines = [
        "<!--",
        "AUTO-GENERATED FILE — DO NOT HAND-EDIT",
        "Regenerated by scripts/generate_content.py from the Shows form",
        'responses where "Is this an Open Mic?" = Yes.',
        f"Last generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "-->",
        "",
        "### Recently Submitted\n",
        '<div class="openmic-table-wrap">',
        '<table class="openmic-table">',
        "<thead><tr><th>Open Mic</th><th>Venue</th><th>Day / Time</th>"
        "<th>Contact</th><th>Notes</th><th>Last Verified</th></tr></thead>",
        "<tbody>",
    ]

    for r in submitted:
        name = escape_html(r.get("Show name", "Untitled"))
        venue = escape_html(r.get("Venue", ""))
        d = parse_date_safe(r.get("Date", ""))
        when = d.strftime("%a, %b %-d") if d else ""
        recurring = r.get(
            "Is this a recurring show? If so, how frequently? Weekly? Monthly?", ""
        ).strip()
        when_label = f"{recurring} ({when})" if recurring and when else (recurring or when or "—")
        link = r.get("Link to where folks can buy tickets", "").strip()
        contact = f'<a href="{escape_html(link)}" target="_blank">link</a>' if link else "—"
        submitted_date = date.today().strftime("%Y-%m-%d")

        lines.append(
            "<tr>"
            f"<td>{name}</td>"
            f"<td>{venue}</td>"
            f"<td>{escape_html(when_label)}</td>"
            f"<td>{contact}</td>"
            f"<td>—</td>"
            f'<td class="last-verified">{submitted_date}</td>'
            "</tr>"
        )

    lines.append("</tbody></table></div>")
    return "\n".join(lines)


def build_openmics_content(rows: list[dict]) -> str:
    if not rows:
        return (
            "::: {.aside-note}\n"
            "Open mic data hasn't been connected yet. Set OPENMICS_CSV_URL "
            "in scripts/generate_content.py once the sheet is published.\n"
            ":::\n"
        )

    today_str = date.today().strftime("%Y-%m-%d")

    # Be tolerant of whatever column names the source sheet actually uses.
    def pick(row, *candidates):
        for c in candidates:
            if c in row and row[c]:
                return row[c]
        return ""

    lines = [
        "<!--",
        "AUTO-GENERATED FILE — DO NOT HAND-EDIT",
        "Regenerated by scripts/generate_content.py from the open mic",
        "listing sheet.",
        f"Last generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "-->",
        "",
        '<div class="openmic-table-wrap">',
        '<table class="openmic-table">',
        "<thead><tr>",
        "<th>Open Mic</th><th>Venue</th><th>Day / Time</th>"
        "<th>Sign-up</th><th>Cost</th><th>Last Verified</th>",
        "</tr></thead>",
        "<tbody>",
    ]

    for r in rows:
        name = escape_html(pick(r, "Open Mic Name", "Name", "Mic"))
        venue = escape_html(pick(r, "Venue", "Location", "Address"))
        when = escape_html(pick(r, "Day / Time", "Day", "Time", "Schedule"))
        signup = escape_html(pick(r, "Sign-up", "Sign Up", "How to Sign Up"))
        cost = escape_html(pick(r, "Cost", "Price")) or "—"
        # If the source sheet already tracks its own verification date,
        # respect it. Otherwise stamp today's date as of this sync.
        last_verified = pick(r, "Last Verified", "Last Checked") or today_str

        link = pick(r, "Link", "Website", "Instagram")
        name_cell = f'<a href="{escape_html(link)}" target="_blank">{name}</a>' if link else name

        lines.append(
            "<tr>"
            f"<td>{name_cell}</td>"
            f"<td>{venue}</td>"
            f"<td>{when}</td>"
            f"<td>{signup}</td>"
            f"<td>{cost}</td>"
            f'<td class="last-verified">{escape_html(last_verified)}</td>'
            "</tr>"
        )

    lines.append("</tbody></table></div>")
    return "\n".join(lines)


# --------------------------- MAIN ---------------------------

def write_file(path: str, content: str):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.rstrip() + "\n")
    print(f"wrote {path}")


def main():
    any_run = False

    if SHOWS_CSV_URL:
        rows = fetch_csv_rows(SHOWS_CSV_URL)
        write_file(f"{OUTPUT_DIR}/shows-content.qmd", build_shows_content(rows))
        write_file(f"{OUTPUT_DIR}/openmics-submitted.qmd", build_submitted_openmics_content(rows))
        any_run = True

    if COMEDIANS_CSV_URL:
        rows = fetch_csv_rows(COMEDIANS_CSV_URL)
        write_file(f"{OUTPUT_DIR}/comedians-content.qmd", build_comedians_content(rows))
        any_run = True

    if OPENMICS_CSV_URL:
        rows = fetch_csv_rows(OPENMICS_CSV_URL)
        write_file(f"{OUTPUT_DIR}/openmics-content.qmd", build_openmics_content(rows))
        any_run = True

    if not any_run:
        print(
            "No CSV URLs configured yet — nothing to do. "
            "Set SHOWS_CSV_URL / COMEDIANS_CSV_URL / OPENMICS_CSV_URL "
            "at the top of scripts/generate_content.py.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
